[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
via-ir = true

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
