[profile.default]
evm_version = "cancun"
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
via-ir = true

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true


[profile.default.optimizer_details.yulDetails]
# see https://book.getfoundry.sh/reference/config/solidity-compiler#optimizer_detailsyul_details
# and https://docs.soliditylang.org/en/latest/using-the-compiler.html#compiler-input-and-output-json-description
optimizerSteps = "dhfoDgvulfnTUtnIf"
